### ISSUE TITLE
Crash upon game launch

### ISSUE THREAD

**Issue by chris819t** [spoorn/SeeThroughLava#5]
Here is the latest.log
All my mods work fine without this mod but when using this mod I cant even launch the game
https://pastebin.com/RXMStSrk
Im not sure if you needed the latest.log or the crash log

**Comment by spoorn** [comment]
Could you see if removing Optifine fixes the crash?  I'm thinking Optifine mixins to the fog handling code so it'll conflict with SeeThroughLava

**Comment by chris819t** [comment]
Yea, it did. I went back to using iris instead

**Comment by spoorn** [comment]
This won't be compatible with Optifine as Optifine changes the fog
