### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by RedstoneBattery** [spoorn/SeeThroughLava#6]
I seem to have a conflict with Origins:

	- apoli 2.2.2 via origins
...
@Redirect conflict. Skipping seethroughlava.mixins.json:BackgroundRendererMixin->@Redirect::changeFogEndInOther(FLnet/minecraft/class_4184;Lnet/minecraft/class_758$class_4596;FZ)V from mod seethroughlava with priority 1000, already redirected by apoli.mixins.json:BackgroundRendererMixin->@Redirect::redirectFogEnd(FLnet/minecraft/class_4184;Lnet/minecraft/class_758$class_4596;)V from mod apoli with priority 1000

**Comment by spoorn** [comment]
Origins conflicting again - seems they changed their fog mixins.  Will fix in the next release
