### ISSUE TITLE
The Lava portion of the mod just stopped working.

### ISSUE THREAD

**Issue by KMFrench1** [spoorn/SeeThroughLava#7]
After updating Fabric and my mods to the latest versions. I can no long see in lava.
The water part still works fine.
Minecraft 1.18.1

**Comment by spoorn** [comment]
What mods are you using?  And versions of those + Fabric?

**Comment by KMFrench1** [comment]
I am using over 300 mods, but just for you :) I played the game of lets remove each mod until clearview starts working.
The mod causing the issue is https://www.curseforge.com/minecraft/mc-mods/the-wild-mod

**Comment by spoorn** [comment]
Thanks for finding the conflict!  That mod is completely overwriting the applyFog method, but in an odd way by rewriting it exactly as it is: https://github.com/Osmiooo/wildmod/blob/eed6b5386584edbada6ccfd1859875871d145e56/src/main/java/frozenblock/wild/mod/mixins/BackgroundRendererMixin.java#L28

Don't think it should be doing that, but I can fix it on my end to override the fog
