### ISSUE TITLE
1.17 support

### ISSUE THREAD

**Issue by justlukie** [spoorn/SeeThroughLava#8]
There are 10s of comments for this mod on curseforge asking for 1.17 support and I too would very much like to see this. It is unfortunate that you went straight to 1.18 from 1.16.

**Comment by spoorn** [comment]
1.17 barely adds any content, so I don't think it's worth the effort to port and maintain for 1.17.  Those 10s of comments were during the time before 1.18 was out, and when I was on hiatus
